// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Thrifty.Infrastructure.Persistence;

#nullable disable

namespace Thrifty.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260930081811_SeedTransactionHistory")]
    partial class SeedTransactionHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Thrifty.Domain.Entities.Budget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<long>("Limit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Category", "Year", "Month")
                        .IsUnique();

                    b.ToTable("Budgets", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Food",
                            Limit = 75000L,
                            Month = 9,
                            Year = 2026
                        },
                        new
                        {
                            Id = 2,
                            Category = "Housing",
                            Limit = 70000L,
                            Month = 9,
                            Year = 2026
                        },
                        new
                        {
                            Id = 3,
                            Category = "Transport",
                            Limit = 40000L,
                            Month = 9,
                            Year = 2026
                        },
                        new
                        {
                            Id = 4,
                            Category = "Shopping",
                            Limit = 30000L,
                            Month = 9,
                            Year = 2026
                        },
                        new
                        {
                            Id = 5,
                            Category = "Bills",
                            Limit = 30000L,
                            Month = 9,
                            Year = 2026
                        },
                        new
                        {
                            Id = 6,
                            Category = "Other",
                            Limit = 55000L,
                            Month = 9,
                            Year = 2026
                        });
                });

            modelBuilder.Entity("Thrifty.Domain.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Merchant")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.ToTable("Transactions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = -4620L,
                            Category = "Food",
                            Date = new DateOnly(2026, 9, 18),
                            Merchant = "Din Tai Fung",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 2,
                            Amount = -6235L,
                            Category = "Food",
                            Date = new DateOnly(2026, 9, 18),
                            Merchant = "NTUC FairPrice",
                            PaymentMethod = "PayNow"
                        },
                        new
                        {
                            Id = 3,
                            Amount = -1480L,
                            Category = "Transport",
                            Date = new DateOnly(2026, 9, 17),
                            Merchant = "Grab ride",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 4,
                            Amount = -11840L,
                            Category = "Bills",
                            Date = new DateOnly(2026, 9, 15),
                            Merchant = "SP Services",
                            PaymentMethod = "GIRO"
                        },
                        new
                        {
                            Id = 5,
                            Amount = -8990L,
                            Category = "Shopping",
                            Date = new DateOnly(2026, 9, 14),
                            Merchant = "Uniqlo",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 6,
                            Amount = 520000L,
                            Category = "Income",
                            Date = new DateOnly(2026, 9, 1),
                            Merchant = "Salary",
                            PaymentMethod = "Bank transfer"
                        },
                        new
                        {
                            Id = 7,
                            Amount = 520000L,
                            Category = "Income",
                            Date = new DateOnly(2026, 4, 1),
                            Merchant = "Salary",
                            PaymentMethod = "Bank transfer"
                        },
                        new
                        {
                            Id = 8,
                            Amount = -7800L,
                            Category = "Housing",
                            Date = new DateOnly(2026, 4, 2),
                            Merchant = "Town Council S&CC",
                            PaymentMethod = "GIRO"
                        },
                        new
                        {
                            Id = 9,
                            Amount = -4800L,
                            Category = "Bills",
                            Date = new DateOnly(2026, 4, 3),
                            Merchant = "Singtel",
                            PaymentMethod = "GIRO"
                        },
                        new
                        {
                            Id = 10,
                            Amount = -10000L,
                            Category = "Transport",
                            Date = new DateOnly(2026, 4, 5),
                            Merchant = "SimplyGo",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 11,
                            Amount = -17650L,
                            Category = "Food",
                            Date = new DateOnly(2026, 4, 6),
                            Merchant = "NTUC FairPrice",
                            PaymentMethod = "PayNow"
                        },
                        new
                        {
                            Id = 12,
                            Amount = -5160L,
                            Category = "Bills",
                            Date = new DateOnly(2026, 4, 8),
                            Merchant = "StarHub",
                            PaymentMethod = "GIRO"
                        },
                        new
                        {
                            Id = 13,
                            Amount = -4260L,
                            Category = "Food",
                            Date = new DateOnly(2026, 4, 9),
                            Merchant = "Kopitiam",
                            PaymentMethod = "PayNow"
                        },
                        new
                        {
                            Id = 14,
                            Amount = -7180L,
                            Category = "Food",
                            Date = new DateOnly(2026, 4, 11),
                            Merchant = "Din Tai Fung",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 15,
                            Amount = -12000L,
                            Category = "Housing",
                            Date = new DateOnly(2026, 4, 12),
                            Merchant = "Helpling",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 16,
                            Amount = -18650L,
                            Category = "Housing",
                            Date = new DateOnly(2026, 4, 14),
                            Merchant = "IKEA",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 17,
                            Amount = -10820L,
                            Category = "Bills",
                            Date = new DateOnly(2026, 4, 15),
                            Merchant = "SP Services",
                            PaymentMethod = "GIRO"
                        },
                        new
                        {
                            Id = 18,
                            Amount = -6440L,
                            Category = "Transport",
                            Date = new DateOnly(2026, 4, 18),
                            Merchant = "Grab ride",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 19,
                            Amount = -8000L,
                            Category = "Transport",
                            Date = new DateOnly(2026, 4, 19),
                            Merchant = "SimplyGo",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 20,
                            Amount = -8490L,
                            Category = "Shopping",
                            Date = new DateOnly(2026, 4, 19),
                            Merchant = "Uniqlo",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 21,
                            Amount = -9230L,
                            Category = "Food",
                            Date = new DateOnly(2026, 4, 20),
                            Merchant = "NTUC FairPrice",
                            PaymentMethod = "PayNow"
                        },
                        new
                        {
                            Id = 22,
                            Amount = -8860L,
                            Category = "Food",
                            Date = new DateOnly(2026, 4, 24),
                            Merchant = "Sheng Siong",
                            PaymentMethod = "PayNow"
                        },
                        new
                        {
                            Id = 23,
                            Amount = -4870L,
                            Category = "Shopping",
                            Date = new DateOnly(2026, 4, 25),
                            Merchant = "Watsons",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 24,
                            Amount = -9600L,
                            Category = "Housing",
                            Date = new DateOnly(2026, 4, 26),
                            Merchant = "Helpling",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 25,
                            Amount = -13200L,
                            Category = "Food",
                            Date = new DateOnly(2026, 4, 26),
                            Merchant = "Hai Di Lao",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 26,
                            Amount = -67870L,
                            Category = "Housing",
                            Date = new DateOnly(2026, 4, 27),
                            Merchant = "Fortytwo",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 27,
                            Amount = -6120L,
                            Category = "Transport",
                            Date = new DateOnly(2026, 4, 28),
                            Merchant = "Grab ride",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 28,
                            Amount = 520000L,
                            Category = "Income",
                            Date = new DateOnly(2026, 5, 1),
                            Merchant = "Salary",
                            PaymentMethod = "Bank transfer"
                        },
                        new
                        {
                            Id = 29,
                            Amount = -7800L,
                            Category = "Housing",
                            Date = new DateOnly(2026, 5, 2),
                            Merchant = "Town Council S&CC",
                            PaymentMethod = "GIRO"
                        },
                        new
                        {
                            Id = 30,
                            Amount = -4800L,
                            Category = "Bills",
                            Date = new DateOnly(2026, 5, 3),
                            Merchant = "Singtel",
                            PaymentMethod = "GIRO"
                        },
                        new
                        {
                            Id = 31,
                            Amount = -15820L,
                            Category = "Food",
                            Date = new DateOnly(2026, 5, 4),
                            Merchant = "NTUC FairPrice",
                            PaymentMethod = "PayNow"
                        },
                        new
                        {
                            Id = 32,
                            Amount = -10000L,
                            Category = "Transport",
                            Date = new DateOnly(2026, 5, 5),
                            Merchant = "SimplyGo",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 33,
                            Amount = -5160L,
                            Category = "Bills",
                            Date = new DateOnly(2026, 5, 8),
                            Merchant = "StarHub",
                            PaymentMethod = "GIRO"
                        },
                        new
                        {
                            Id = 34,
                            Amount = -4260L,
                            Category = "Food",
                            Date = new DateOnly(2026, 5, 9),
                            Merchant = "Kopitiam",
                            PaymentMethod = "PayNow"
                        },
                        new
                        {
                            Id = 35,
                            Amount = -7230L,
                            Category = "Transport",
                            Date = new DateOnly(2026, 5, 9),
                            Merchant = "Grab ride",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 36,
                            Amount = -18600L,
                            Category = "Food",
                            Date = new DateOnly(2026, 5, 11),
                            Merchant = "Jumbo Seafood",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 37,
                            Amount = -12000L,
                            Category = "Housing",
                            Date = new DateOnly(2026, 5, 12),
                            Merchant = "Helpling",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 38,
                            Amount = -18650L,
                            Category = "Housing",
                            Date = new DateOnly(2026, 5, 14),
                            Merchant = "IKEA",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 39,
                            Amount = -11260L,
                            Category = "Bills",
                            Date = new DateOnly(2026, 5, 15),
                            Merchant = "SP Services",
                            PaymentMethod = "GIRO"
                        },
                        new
                        {
                            Id = 40,
                            Amount = -6340L,
                            Category = "Shopping",
                            Date = new DateOnly(2026, 5, 16),
                            Merchant = "Shopee",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 41,
                            Amount = -10470L,
                            Category = "Food",
                            Date = new DateOnly(2026, 5, 18),
                            Merchant = "NTUC FairPrice",
                            PaymentMethod = "PayNow"
                        },
                        new
                        {
                            Id = 42,
                            Amount = -8000L,
                            Category = "Transport",
                            Date = new DateOnly(2026, 5, 19),
                            Merchant = "SimplyGo",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 43,
                            Amount = -7690L,
                            Category = "Food",
                            Date = new DateOnly(2026, 5, 23),
                            Merchant = "Sheng Siong",
                            PaymentMethod = "PayNow"
                        },
                        new
                        {
                            Id = 44,
                            Amount = -92480L,
                            Category = "Shopping",
                            Date = new DateOnly(2026, 5, 24),
                            Merchant = "Courts",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 45,
                            Amount = -4870L,
                            Category = "Shopping",
                            Date = new DateOnly(2026, 5, 25),
                            Merchant = "Watsons",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 46,
                            Amount = -9600L,
                            Category = "Housing",
                            Date = new DateOnly(2026, 5, 26),
                            Merchant = "Helpling",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 47,
                            Amount = -6120L,
                            Category = "Transport",
                            Date = new DateOnly(2026, 5, 28),
                            Merchant = "Grab ride",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 48,
                            Amount = -3850L,
                            Category = "Food",
                            Date = new DateOnly(2026, 5, 29),
                            Merchant = "Kopitiam",
                            PaymentMethod = "PayNow"
                        },
                        new
                        {
                            Id = 49,
                            Amount = 520000L,
                            Category = "Income",
                            Date = new DateOnly(2026, 6, 1),
                            Merchant = "Salary",
                            PaymentMethod = "Bank transfer"
                        },
                        new
                        {
                            Id = 50,
                            Amount = -7800L,
                            Category = "Housing",
                            Date = new DateOnly(2026, 6, 2),
                            Merchant = "Town Council S&CC",
                            PaymentMethod = "GIRO"
                        },
                        new
                        {
                            Id = 51,
                            Amount = -4800L,
                            Category = "Bills",
                            Date = new DateOnly(2026, 6, 3),
                            Merchant = "Singtel",
                            PaymentMethod = "GIRO"
                        },
                        new
                        {
                            Id = 52,
                            Amount = -10000L,
                            Category = "Transport",
                            Date = new DateOnly(2026, 6, 5),
                            Merchant = "SimplyGo",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 53,
                            Amount = -16890L,
                            Category = "Food",
                            Date = new DateOnly(2026, 6, 7),
                            Merchant = "NTUC FairPrice",
                            PaymentMethod = "PayNow"
                        },
                        new
                        {
                            Id = 54,
                            Amount = -5160L,
                            Category = "Bills",
                            Date = new DateOnly(2026, 6, 8),
                            Merchant = "StarHub",
                            PaymentMethod = "GIRO"
                        },
                        new
                        {
                            Id = 55,
                            Amount = -4260L,
                            Category = "Food",
                            Date = new DateOnly(2026, 6, 9),
                            Merchant = "Kopitiam",
                            PaymentMethod = "PayNow"
                        },
                        new
                        {
                            Id = 56,
                            Amount = -12000L,
                            Category = "Housing",
                            Date = new DateOnly(2026, 6, 12),
                            Merchant = "Helpling",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 57,
                            Amount = -5860L,
                            Category = "Transport",
                            Date = new DateOnly(2026, 6, 13),
                            Merchant = "Grab ride",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 58,
                            Amount = -18650L,
                            Category = "Housing",
                            Date = new DateOnly(2026, 6, 14),
                            Merchant = "IKEA",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 59,
                            Amount = -4630L,
                            Category = "Food",
                            Date = new DateOnly(2026, 6, 14),
                            Merchant = "Tim Ho Wan",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 60,
                            Amount = -13180L,
                            Category = "Bills",
                            Date = new DateOnly(2026, 6, 15),
                            Merchant = "SP Services",
                            PaymentMethod = "GIRO"
                        },
                        new
                        {
                            Id = 61,
                            Amount = -8000L,
                            Category = "Transport",
                            Date = new DateOnly(2026, 6, 19),
                            Merchant = "SimplyGo",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 62,
                            Amount = -73710L,
                            Category = "Shopping",
                            Date = new DateOnly(2026, 6, 20),
                            Merchant = "Takashimaya",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 63,
                            Amount = -8840L,
                            Category = "Food",
                            Date = new DateOnly(2026, 6, 21),
                            Merchant = "NTUC FairPrice",
                            PaymentMethod = "PayNow"
                        },
                        new
                        {
                            Id = 64,
                            Amount = -9210L,
                            Category = "Food",
                            Date = new DateOnly(2026, 6, 22),
                            Merchant = "Sheng Siong",
                            PaymentMethod = "PayNow"
                        },
                        new
                        {
                            Id = 65,
                            Amount = -4870L,
                            Category = "Shopping",
                            Date = new DateOnly(2026, 6, 25),
                            Merchant = "Watsons",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 66,
                            Amount = -9600L,
                            Category = "Housing",
                            Date = new DateOnly(2026, 6, 26),
                            Merchant = "Helpling",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 67,
                            Amount = -5420L,
                            Category = "Food",
                            Date = new DateOnly(2026, 6, 27),
                            Merchant = "GrabFood",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 68,
                            Amount = -6120L,
                            Category = "Transport",
                            Date = new DateOnly(2026, 6, 28),
                            Merchant = "Grab ride",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 69,
                            Amount = 520000L,
                            Category = "Income",
                            Date = new DateOnly(2026, 7, 1),
                            Merchant = "Salary",
                            PaymentMethod = "Bank transfer"
                        },
                        new
                        {
                            Id = 70,
                            Amount = -7800L,
                            Category = "Housing",
                            Date = new DateOnly(2026, 7, 2),
                            Merchant = "Town Council S&CC",
                            PaymentMethod = "GIRO"
                        },
                        new
                        {
                            Id = 71,
                            Amount = -4800L,
                            Category = "Bills",
                            Date = new DateOnly(2026, 7, 3),
                            Merchant = "Singtel",
                            PaymentMethod = "GIRO"
                        },
                        new
                        {
                            Id = 72,
                            Amount = -10000L,
                            Category = "Transport",
                            Date = new DateOnly(2026, 7, 5),
                            Merchant = "SimplyGo",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 73,
                            Amount = -18160L,
                            Category = "Food",
                            Date = new DateOnly(2026, 7, 5),
                            Merchant = "NTUC FairPrice",
                            PaymentMethod = "PayNow"
                        },
                        new
                        {
                            Id = 74,
                            Amount = -5160L,
                            Category = "Bills",
                            Date = new DateOnly(2026, 7, 8),
                            Merchant = "StarHub",
                            PaymentMethod = "GIRO"
                        },
                        new
                        {
                            Id = 75,
                            Amount = -4260L,
                            Category = "Food",
                            Date = new DateOnly(2026, 7, 9),
                            Merchant = "Kopitiam",
                            PaymentMethod = "PayNow"
                        },
                        new
                        {
                            Id = 76,
                            Amount = -8270L,
                            Category = "Transport",
                            Date = new DateOnly(2026, 7, 10),
                            Merchant = "Grab ride",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 77,
                            Amount = -12000L,
                            Category = "Housing",
                            Date = new DateOnly(2026, 7, 12),
                            Merchant = "Helpling",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 78,
                            Amount = -6490L,
                            Category = "Food",
                            Date = new DateOnly(2026, 7, 12),
                            Merchant = "Din Tai Fung",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 79,
                            Amount = -18650L,
                            Category = "Housing",
                            Date = new DateOnly(2026, 7, 14),
                            Merchant = "IKEA",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 80,
                            Amount = -13850L,
                            Category = "Bills",
                            Date = new DateOnly(2026, 7, 15),
                            Merchant = "SP Services",
                            PaymentMethod = "GIRO"
                        },
                        new
                        {
                            Id = 81,
                            Amount = -9280L,
                            Category = "Shopping",
                            Date = new DateOnly(2026, 7, 17),
                            Merchant = "Lazada",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 82,
                            Amount = -8000L,
                            Category = "Transport",
                            Date = new DateOnly(2026, 7, 19),
                            Merchant = "SimplyGo",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 83,
                            Amount = -9740L,
                            Category = "Food",
                            Date = new DateOnly(2026, 7, 19),
                            Merchant = "NTUC FairPrice",
                            PaymentMethod = "PayNow"
                        },
                        new
                        {
                            Id = 84,
                            Amount = -8320L,
                            Category = "Food",
                            Date = new DateOnly(2026, 7, 24),
                            Merchant = "Sheng Siong",
                            PaymentMethod = "PayNow"
                        },
                        new
                        {
                            Id = 85,
                            Amount = -4870L,
                            Category = "Shopping",
                            Date = new DateOnly(2026, 7, 25),
                            Merchant = "Watsons",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 86,
                            Amount = -9600L,
                            Category = "Housing",
                            Date = new DateOnly(2026, 7, 26),
                            Merchant = "Helpling",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 87,
                            Amount = -4130L,
                            Category = "Food",
                            Date = new DateOnly(2026, 7, 26),
                            Merchant = "Swee Choon",
                            PaymentMethod = "PayNow"
                        },
                        new
                        {
                            Id = 88,
                            Amount = -6120L,
                            Category = "Transport",
                            Date = new DateOnly(2026, 7, 28),
                            Merchant = "Grab ride",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 89,
                            Amount = -103500L,
                            Category = "Other",
                            Date = new DateOnly(2026, 7, 30),
                            Merchant = "Scoot",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 90,
                            Amount = 520000L,
                            Category = "Income",
                            Date = new DateOnly(2026, 8, 1),
                            Merchant = "Salary",
                            PaymentMethod = "Bank transfer"
                        },
                        new
                        {
                            Id = 91,
                            Amount = -7800L,
                            Category = "Housing",
                            Date = new DateOnly(2026, 8, 2),
                            Merchant = "Town Council S&CC",
                            PaymentMethod = "GIRO"
                        },
                        new
                        {
                            Id = 92,
                            Amount = -4800L,
                            Category = "Bills",
                            Date = new DateOnly(2026, 8, 3),
                            Merchant = "Singtel",
                            PaymentMethod = "GIRO"
                        },
                        new
                        {
                            Id = 93,
                            Amount = -18640L,
                            Category = "Food",
                            Date = new DateOnly(2026, 8, 3),
                            Merchant = "NTUC FairPrice",
                            PaymentMethod = "PayNow"
                        },
                        new
                        {
                            Id = 94,
                            Amount = -12000L,
                            Category = "Transport",
                            Date = new DateOnly(2026, 8, 5),
                            Merchant = "SimplyGo",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 95,
                            Amount = -5160L,
                            Category = "Bills",
                            Date = new DateOnly(2026, 8, 8),
                            Merchant = "StarHub",
                            PaymentMethod = "GIRO"
                        },
                        new
                        {
                            Id = 96,
                            Amount = -11980L,
                            Category = "Shopping",
                            Date = new DateOnly(2026, 8, 8),
                            Merchant = "Uniqlo",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 97,
                            Amount = -5830L,
                            Category = "Food",
                            Date = new DateOnly(2026, 8, 9),
                            Merchant = "Din Tai Fung",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 98,
                            Amount = -9560L,
                            Category = "Food",
                            Date = new DateOnly(2026, 8, 10),
                            Merchant = "Sheng Siong",
                            PaymentMethod = "PayNow"
                        },
                        new
                        {
                            Id = 99,
                            Amount = -12000L,
                            Category = "Housing",
                            Date = new DateOnly(2026, 8, 12),
                            Merchant = "Helpling",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 100,
                            Amount = -8840L,
                            Category = "Transport",
                            Date = new DateOnly(2026, 8, 13),
                            Merchant = "Grab ride",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 101,
                            Amount = -12540L,
                            Category = "Bills",
                            Date = new DateOnly(2026, 8, 15),
                            Merchant = "SP Services",
                            PaymentMethod = "GIRO"
                        },
                        new
                        {
                            Id = 102,
                            Amount = -14200L,
                            Category = "Food",
                            Date = new DateOnly(2026, 8, 16),
                            Merchant = "Jumbo Seafood",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 103,
                            Amount = -21400L,
                            Category = "Housing",
                            Date = new DateOnly(2026, 8, 17),
                            Merchant = "IKEA",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 104,
                            Amount = -7830L,
                            Category = "Shopping",
                            Date = new DateOnly(2026, 8, 18),
                            Merchant = "Shopee",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 105,
                            Amount = -8000L,
                            Category = "Transport",
                            Date = new DateOnly(2026, 8, 19),
                            Merchant = "SimplyGo",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 106,
                            Amount = -10400L,
                            Category = "Housing",
                            Date = new DateOnly(2026, 8, 20),
                            Merchant = "Mr DIY",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 107,
                            Amount = -6470L,
                            Category = "Food",
                            Date = new DateOnly(2026, 8, 22),
                            Merchant = "GrabFood",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 108,
                            Amount = -20000L,
                            Category = "Other",
                            Date = new DateOnly(2026, 8, 23),
                            Merchant = "Wedding ang bao",
                            PaymentMethod = "PayNow"
                        },
                        new
                        {
                            Id = 109,
                            Amount = -8000L,
                            Category = "Food",
                            Date = new DateOnly(2026, 8, 24),
                            Merchant = "NTUC FairPrice",
                            PaymentMethod = "PayNow"
                        },
                        new
                        {
                            Id = 110,
                            Amount = -5490L,
                            Category = "Shopping",
                            Date = new DateOnly(2026, 8, 25),
                            Merchant = "Watsons",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 111,
                            Amount = -9600L,
                            Category = "Housing",
                            Date = new DateOnly(2026, 8, 26),
                            Merchant = "Helpling",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 112,
                            Amount = -4500L,
                            Category = "Food",
                            Date = new DateOnly(2026, 8, 28),
                            Merchant = "Kopitiam",
                            PaymentMethod = "PayNow"
                        },
                        new
                        {
                            Id = 113,
                            Amount = -5960L,
                            Category = "Transport",
                            Date = new DateOnly(2026, 8, 29),
                            Merchant = "Grab ride",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 114,
                            Amount = -1300L,
                            Category = "Other",
                            Date = new DateOnly(2026, 8, 30),
                            Merchant = "SPCA donation",
                            PaymentMethod = "PayNow"
                        },
                        new
                        {
                            Id = 115,
                            Amount = -3840L,
                            Category = "Food",
                            Date = new DateOnly(2026, 9, 1),
                            Merchant = "NTUC FairPrice",
                            PaymentMethod = "PayNow"
                        },
                        new
                        {
                            Id = 116,
                            Amount = -860L,
                            Category = "Food",
                            Date = new DateOnly(2026, 9, 1),
                            Merchant = "Toast Box",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 117,
                            Amount = -1300L,
                            Category = "Transport",
                            Date = new DateOnly(2026, 9, 1),
                            Merchant = "SimplyGo",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 118,
                            Amount = -7800L,
                            Category = "Housing",
                            Date = new DateOnly(2026, 9, 2),
                            Merchant = "Town Council S&CC",
                            PaymentMethod = "GIRO"
                        },
                        new
                        {
                            Id = 119,
                            Amount = -720L,
                            Category = "Food",
                            Date = new DateOnly(2026, 9, 2),
                            Merchant = "Ya Kun Kaya Toast",
                            PaymentMethod = "PayNow"
                        },
                        new
                        {
                            Id = 120,
                            Amount = -2480L,
                            Category = "Transport",
                            Date = new DateOnly(2026, 9, 2),
                            Merchant = "Grab ride",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 121,
                            Amount = -4800L,
                            Category = "Bills",
                            Date = new DateOnly(2026, 9, 3),
                            Merchant = "Singtel",
                            PaymentMethod = "GIRO"
                        },
                        new
                        {
                            Id = 122,
                            Amount = -650L,
                            Category = "Food",
                            Date = new DateOnly(2026, 9, 3),
                            Merchant = "Koufu",
                            PaymentMethod = "PayNow"
                        },
                        new
                        {
                            Id = 123,
                            Amount = -4050L,
                            Category = "Shopping",
                            Date = new DateOnly(2026, 9, 3),
                            Merchant = "Popular Bookstore",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 124,
                            Amount = -18900L,
                            Category = "Housing",
                            Date = new DateOnly(2026, 9, 4),
                            Merchant = "Fortytwo",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 125,
                            Amount = -3900L,
                            Category = "Housing",
                            Date = new DateOnly(2026, 9, 4),
                            Merchant = "Mr DIY",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 126,
                            Amount = -2940L,
                            Category = "Food",
                            Date = new DateOnly(2026, 9, 4),
                            Merchant = "Sheng Siong",
                            PaymentMethod = "PayNow"
                        },
                        new
                        {
                            Id = 127,
                            Amount = -1460L,
                            Category = "Food",
                            Date = new DateOnly(2026, 9, 4),
                            Merchant = "Kopitiam",
                            PaymentMethod = "PayNow"
                        },
                        new
                        {
                            Id = 128,
                            Amount = -4000L,
                            Category = "Transport",
                            Date = new DateOnly(2026, 9, 4),
                            Merchant = "Grab ride",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 129,
                            Amount = -2000L,
                            Category = "Transport",
                            Date = new DateOnly(2026, 9, 5),
                            Merchant = "SimplyGo",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 130,
                            Amount = -1290L,
                            Category = "Food",
                            Date = new DateOnly(2026, 9, 5),
                            Merchant = "McDonald's",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 131,
                            Amount = -1210L,
                            Category = "Food",
                            Date = new DateOnly(2026, 9, 5),
                            Merchant = "Starbucks",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 132,
                            Amount = -4230L,
                            Category = "Food",
                            Date = new DateOnly(2026, 9, 6),
                            Merchant = "NTUC FairPrice",
                            PaymentMethod = "PayNow"
                        },
                        new
                        {
                            Id = 133,
                            Amount = -1170L,
                            Category = "Food",
                            Date = new DateOnly(2026, 9, 6),
                            Merchant = "Maxwell Food Centre",
                            PaymentMethod = "PayNow"
                        },
                        new
                        {
                            Id = 134,
                            Amount = -1600L,
                            Category = "Transport",
                            Date = new DateOnly(2026, 9, 6),
                            Merchant = "Grab ride",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 135,
                            Amount = -9800L,
                            Category = "Food",
                            Date = new DateOnly(2026, 9, 7),
                            Merchant = "Jumbo Seafood",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 136,
                            Amount = -3200L,
                            Category = "Transport",
                            Date = new DateOnly(2026, 9, 7),
                            Merchant = "Grab ride",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 137,
                            Amount = -5160L,
                            Category = "Bills",
                            Date = new DateOnly(2026, 9, 8),
                            Merchant = "StarHub",
                            PaymentMethod = "GIRO"
                        },
                        new
                        {
                            Id = 138,
                            Amount = -540L,
                            Category = "Food",
                            Date = new DateOnly(2026, 9, 8),
                            Merchant = "Old Chang Kee",
                            PaymentMethod = "PayNow"
                        },
                        new
                        {
                            Id = 139,
                            Amount = -3100L,
                            Category = "Shopping",
                            Date = new DateOnly(2026, 9, 8),
                            Merchant = "Watsons",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 140,
                            Amount = -6000L,
                            Category = "Housing",
                            Date = new DateOnly(2026, 9, 9),
                            Merchant = "Helpling",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 141,
                            Amount = -7000L,
                            Category = "Food",
                            Date = new DateOnly(2026, 9, 9),
                            Merchant = "Hai Di Lao",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 142,
                            Amount = -2000L,
                            Category = "Transport",
                            Date = new DateOnly(2026, 9, 9),
                            Merchant = "SimplyGo",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 143,
                            Amount = -5490L,
                            Category = "Shopping",
                            Date = new DateOnly(2026, 9, 10),
                            Merchant = "Shopee",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 144,
                            Amount = -710L,
                            Category = "Food",
                            Date = new DateOnly(2026, 9, 10),
                            Merchant = "Toast Box",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 145,
                            Amount = -1000L,
                            Category = "Food",
                            Date = new DateOnly(2026, 9, 10),
                            Merchant = "GrabFood",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 146,
                            Amount = -9600L,
                            Category = "Housing",
                            Date = new DateOnly(2026, 9, 11),
                            Merchant = "CoolTech Aircon",
                            PaymentMethod = "PayNow"
                        },
                        new
                        {
                            Id = 147,
                            Amount = -2985L,
                            Category = "Food",
                            Date = new DateOnly(2026, 9, 11),
                            Merchant = "NTUC FairPrice",
                            PaymentMethod = "PayNow"
                        },
                        new
                        {
                            Id = 148,
                            Amount = -1415L,
                            Category = "Food",
                            Date = new DateOnly(2026, 9, 11),
                            Merchant = "Tim Ho Wan",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 149,
                            Amount = -2240L,
                            Category = "Shopping",
                            Date = new DateOnly(2026, 9, 12),
                            Merchant = "Guardian",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 150,
                            Amount = -3260L,
                            Category = "Food",
                            Date = new DateOnly(2026, 9, 12),
                            Merchant = "Swee Choon",
                            PaymentMethod = "PayNow"
                        },
                        new
                        {
                            Id = 151,
                            Amount = -7480L,
                            Category = "Shopping",
                            Date = new DateOnly(2026, 9, 13),
                            Merchant = "Lazada",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 152,
                            Amount = -920L,
                            Category = "Food",
                            Date = new DateOnly(2026, 9, 13),
                            Merchant = "Koufu",
                            PaymentMethod = "PayNow"
                        },
                        new
                        {
                            Id = 153,
                            Amount = -2000L,
                            Category = "Transport",
                            Date = new DateOnly(2026, 9, 13),
                            Merchant = "SimplyGo",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 154,
                            Amount = -820L,
                            Category = "Food",
                            Date = new DateOnly(2026, 9, 14),
                            Merchant = "Kopitiam",
                            PaymentMethod = "PayNow"
                        },
                        new
                        {
                            Id = 155,
                            Amount = -2000L,
                            Category = "Transport",
                            Date = new DateOnly(2026, 9, 15),
                            Merchant = "SimplyGo",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 156,
                            Amount = -835L,
                            Category = "Food",
                            Date = new DateOnly(2026, 9, 15),
                            Merchant = "Ya Kun Kaya Toast",
                            PaymentMethod = "PayNow"
                        },
                        new
                        {
                            Id = 157,
                            Amount = -6000L,
                            Category = "Housing",
                            Date = new DateOnly(2026, 9, 16),
                            Merchant = "Helpling",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 158,
                            Amount = -2360L,
                            Category = "Food",
                            Date = new DateOnly(2026, 9, 16),
                            Merchant = "NTUC FairPrice",
                            PaymentMethod = "PayNow"
                        },
                        new
                        {
                            Id = 159,
                            Amount = -4000L,
                            Category = "Transport",
                            Date = new DateOnly(2026, 9, 16),
                            Merchant = "SimplyGo",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 160,
                            Amount = -4200L,
                            Category = "Food",
                            Date = new DateOnly(2026, 9, 17),
                            Merchant = "Ichiban Sushi",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 161,
                            Amount = -9000L,
                            Category = "Housing",
                            Date = new DateOnly(2026, 9, 17),
                            Merchant = "IKEA",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 162,
                            Amount = -4540L,
                            Category = "Transport",
                            Date = new DateOnly(2026, 9, 19),
                            Merchant = "Grab ride",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 163,
                            Amount = -3550L,
                            Category = "Shopping",
                            Date = new DateOnly(2026, 9, 19),
                            Merchant = "Decathlon",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 164,
                            Amount = -2100L,
                            Category = "Food",
                            Date = new DateOnly(2026, 9, 19),
                            Merchant = "Tim Ho Wan",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 165,
                            Amount = -1750L,
                            Category = "Food",
                            Date = new DateOnly(2026, 9, 19),
                            Merchant = "NTUC FairPrice",
                            PaymentMethod = "PayNow"
                        },
                        new
                        {
                            Id = 166,
                            Amount = -980L,
                            Category = "Food",
                            Date = new DateOnly(2026, 9, 19),
                            Merchant = "Starbucks",
                            PaymentMethod = "Credit card"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
