// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Thrifty.Infrastructure.Persistence;

#nullable disable

namespace Thrifty.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Thrifty.Domain.Entities.Budget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<long>("Limit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Category", "Year", "Month")
                        .IsUnique();

                    b.ToTable("Budgets", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Food",
                            Limit = 75000L,
                            Month = 9,
                            Year = 2026
                        },
                        new
                        {
                            Id = 2,
                            Category = "Housing",
                            Limit = 70000L,
                            Month = 9,
                            Year = 2026
                        },
                        new
                        {
                            Id = 3,
                            Category = "Transport",
                            Limit = 40000L,
                            Month = 9,
                            Year = 2026
                        },
                        new
                        {
                            Id = 4,
                            Category = "Shopping",
                            Limit = 30000L,
                            Month = 9,
                            Year = 2026
                        },
                        new
                        {
                            Id = 5,
                            Category = "Bills",
                            Limit = 30000L,
                            Month = 9,
                            Year = 2026
                        },
                        new
                        {
                            Id = 6,
                            Category = "Other",
                            Limit = 55000L,
                            Month = 9,
                            Year = 2026
                        });
                });

            modelBuilder.Entity("Thrifty.Domain.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Merchant")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.ToTable("Transactions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = -4620L,
                            Category = "Food",
                            Date = new DateOnly(2026, 9, 18),
                            Merchant = "Din Tai Fung",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 2,
                            Amount = -6235L,
                            Category = "Food",
                            Date = new DateOnly(2026, 9, 18),
                            Merchant = "NTUC FairPrice",
                            PaymentMethod = "PayNow"
                        },
                        new
                        {
                            Id = 3,
                            Amount = -1480L,
                            Category = "Transport",
                            Date = new DateOnly(2026, 9, 17),
                            Merchant = "Grab ride",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 4,
                            Amount = -11840L,
                            Category = "Bills",
                            Date = new DateOnly(2026, 9, 15),
                            Merchant = "SP Services",
                            PaymentMethod = "GIRO"
                        },
                        new
                        {
                            Id = 5,
                            Amount = -8990L,
                            Category = "Shopping",
                            Date = new DateOnly(2026, 9, 14),
                            Merchant = "Uniqlo",
                            PaymentMethod = "Credit card"
                        },
                        new
                        {
                            Id = 6,
                            Amount = 520000L,
                            Category = "Income",
                            Date = new DateOnly(2026, 9, 1),
                            Merchant = "Salary",
                            PaymentMethod = "Bank transfer"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
