using Thrifty.Domain.Entities;
using Thrifty.Domain.Enums;

namespace Thrifty.Infrastructure.Persistence.Seed
{
    // Ported from Frontend/src/data/mockData.ts. Applied through migrations via HasData.
    internal static class SeedData
    {
        public static readonly Transaction[] Transactions = new Transaction[]
        {
            // September (original mock transactions)
            new Transaction { Id = 1, Date = new DateOnly(2026, 9, 18), Merchant = "Din Tai Fung", Category = CategoryId.Food, PaymentMethod = "Credit card", Amount = -46.20m },
            new Transaction { Id = 2, Date = new DateOnly(2026, 9, 18), Merchant = "NTUC FairPrice", Category = CategoryId.Food, PaymentMethod = "PayNow", Amount = -62.35m },
            new Transaction { Id = 3, Date = new DateOnly(2026, 9, 17), Merchant = "Grab ride", Category = CategoryId.Transport, PaymentMethod = "Credit card", Amount = -14.80m },
            new Transaction { Id = 4, Date = new DateOnly(2026, 9, 15), Merchant = "SP Services", Category = CategoryId.Bills, PaymentMethod = "GIRO", Amount = -118.40m },
            new Transaction { Id = 5, Date = new DateOnly(2026, 9, 14), Merchant = "Uniqlo", Category = CategoryId.Shopping, PaymentMethod = "Credit card", Amount = -89.90m },
            new Transaction { Id = 6, Date = new DateOnly(2026, 9, 1), Merchant = "Salary", Category = CategoryId.Income, PaymentMethod = "Bank transfer", Amount = 5200m },

            // Backfilled history so the computed daily/monthly series and category
            // changes reproduce the frontend mock charts (Sep figures run to 19 Sep).
            // April
            new Transaction { Id = 7, Date = new DateOnly(2026, 4, 1), Merchant = "Salary", Category = CategoryId.Income, PaymentMethod = "Bank transfer", Amount = 5200m },
            new Transaction { Id = 8, Date = new DateOnly(2026, 4, 2), Merchant = "Town Council S&CC", Category = CategoryId.Housing, PaymentMethod = "GIRO", Amount = -78.00m },
            new Transaction { Id = 9, Date = new DateOnly(2026, 4, 3), Merchant = "Singtel", Category = CategoryId.Bills, PaymentMethod = "GIRO", Amount = -48.00m },
            new Transaction { Id = 10, Date = new DateOnly(2026, 4, 5), Merchant = "SimplyGo", Category = CategoryId.Transport, PaymentMethod = "Credit card", Amount = -100.00m },
            new Transaction { Id = 11, Date = new DateOnly(2026, 4, 6), Merchant = "NTUC FairPrice", Category = CategoryId.Food, PaymentMethod = "PayNow", Amount = -176.50m },
            new Transaction { Id = 12, Date = new DateOnly(2026, 4, 8), Merchant = "StarHub", Category = CategoryId.Bills, PaymentMethod = "GIRO", Amount = -51.60m },
            new Transaction { Id = 13, Date = new DateOnly(2026, 4, 9), Merchant = "Kopitiam", Category = CategoryId.Food, PaymentMethod = "PayNow", Amount = -42.60m },
            new Transaction { Id = 14, Date = new DateOnly(2026, 4, 11), Merchant = "Din Tai Fung", Category = CategoryId.Food, PaymentMethod = "Credit card", Amount = -71.80m },
            new Transaction { Id = 15, Date = new DateOnly(2026, 4, 12), Merchant = "Helpling", Category = CategoryId.Housing, PaymentMethod = "Credit card", Amount = -120.00m },
            new Transaction { Id = 16, Date = new DateOnly(2026, 4, 14), Merchant = "IKEA", Category = CategoryId.Housing, PaymentMethod = "Credit card", Amount = -186.50m },
            new Transaction { Id = 17, Date = new DateOnly(2026, 4, 15), Merchant = "SP Services", Category = CategoryId.Bills, PaymentMethod = "GIRO", Amount = -108.20m },
            new Transaction { Id = 18, Date = new DateOnly(2026, 4, 18), Merchant = "Grab ride", Category = CategoryId.Transport, PaymentMethod = "Credit card", Amount = -64.40m },
            new Transaction { Id = 19, Date = new DateOnly(2026, 4, 19), Merchant = "SimplyGo", Category = CategoryId.Transport, PaymentMethod = "Credit card", Amount = -80.00m },
            new Transaction { Id = 20, Date = new DateOnly(2026, 4, 19), Merchant = "Uniqlo", Category = CategoryId.Shopping, PaymentMethod = "Credit card", Amount = -84.90m },
            new Transaction { Id = 21, Date = new DateOnly(2026, 4, 20), Merchant = "NTUC FairPrice", Category = CategoryId.Food, PaymentMethod = "PayNow", Amount = -92.30m },
            new Transaction { Id = 22, Date = new DateOnly(2026, 4, 24), Merchant = "Sheng Siong", Category = CategoryId.Food, PaymentMethod = "PayNow", Amount = -88.60m },
            new Transaction { Id = 23, Date = new DateOnly(2026, 4, 25), Merchant = "Watsons", Category = CategoryId.Shopping, PaymentMethod = "Credit card", Amount = -48.70m },
            new Transaction { Id = 24, Date = new DateOnly(2026, 4, 26), Merchant = "Helpling", Category = CategoryId.Housing, PaymentMethod = "Credit card", Amount = -96.00m },
            new Transaction { Id = 25, Date = new DateOnly(2026, 4, 26), Merchant = "Hai Di Lao", Category = CategoryId.Food, PaymentMethod = "Credit card", Amount = -132.00m },
            new Transaction { Id = 26, Date = new DateOnly(2026, 4, 27), Merchant = "Fortytwo", Category = CategoryId.Housing, PaymentMethod = "Credit card", Amount = -678.70m },
            new Transaction { Id = 27, Date = new DateOnly(2026, 4, 28), Merchant = "Grab ride", Category = CategoryId.Transport, PaymentMethod = "Credit card", Amount = -61.20m },

            // May
            new Transaction { Id = 28, Date = new DateOnly(2026, 5, 1), Merchant = "Salary", Category = CategoryId.Income, PaymentMethod = "Bank transfer", Amount = 5200m },
            new Transaction { Id = 29, Date = new DateOnly(2026, 5, 2), Merchant = "Town Council S&CC", Category = CategoryId.Housing, PaymentMethod = "GIRO", Amount = -78.00m },
            new Transaction { Id = 30, Date = new DateOnly(2026, 5, 3), Merchant = "Singtel", Category = CategoryId.Bills, PaymentMethod = "GIRO", Amount = -48.00m },
            new Transaction { Id = 31, Date = new DateOnly(2026, 5, 4), Merchant = "NTUC FairPrice", Category = CategoryId.Food, PaymentMethod = "PayNow", Amount = -158.20m },
            new Transaction { Id = 32, Date = new DateOnly(2026, 5, 5), Merchant = "SimplyGo", Category = CategoryId.Transport, PaymentMethod = "Credit card", Amount = -100.00m },
            new Transaction { Id = 33, Date = new DateOnly(2026, 5, 8), Merchant = "StarHub", Category = CategoryId.Bills, PaymentMethod = "GIRO", Amount = -51.60m },
            new Transaction { Id = 34, Date = new DateOnly(2026, 5, 9), Merchant = "Kopitiam", Category = CategoryId.Food, PaymentMethod = "PayNow", Amount = -42.60m },
            new Transaction { Id = 35, Date = new DateOnly(2026, 5, 9), Merchant = "Grab ride", Category = CategoryId.Transport, PaymentMethod = "Credit card", Amount = -72.30m },
            new Transaction { Id = 36, Date = new DateOnly(2026, 5, 11), Merchant = "Jumbo Seafood", Category = CategoryId.Food, PaymentMethod = "Credit card", Amount = -186.00m },
            new Transaction { Id = 37, Date = new DateOnly(2026, 5, 12), Merchant = "Helpling", Category = CategoryId.Housing, PaymentMethod = "Credit card", Amount = -120.00m },
            new Transaction { Id = 38, Date = new DateOnly(2026, 5, 14), Merchant = "IKEA", Category = CategoryId.Housing, PaymentMethod = "Credit card", Amount = -186.50m },
            new Transaction { Id = 39, Date = new DateOnly(2026, 5, 15), Merchant = "SP Services", Category = CategoryId.Bills, PaymentMethod = "GIRO", Amount = -112.60m },
            new Transaction { Id = 40, Date = new DateOnly(2026, 5, 16), Merchant = "Shopee", Category = CategoryId.Shopping, PaymentMethod = "Credit card", Amount = -63.40m },
            new Transaction { Id = 41, Date = new DateOnly(2026, 5, 18), Merchant = "NTUC FairPrice", Category = CategoryId.Food, PaymentMethod = "PayNow", Amount = -104.70m },
            new Transaction { Id = 42, Date = new DateOnly(2026, 5, 19), Merchant = "SimplyGo", Category = CategoryId.Transport, PaymentMethod = "Credit card", Amount = -80.00m },
            new Transaction { Id = 43, Date = new DateOnly(2026, 5, 23), Merchant = "Sheng Siong", Category = CategoryId.Food, PaymentMethod = "PayNow", Amount = -76.90m },
            new Transaction { Id = 44, Date = new DateOnly(2026, 5, 24), Merchant = "Courts", Category = CategoryId.Shopping, PaymentMethod = "Credit card", Amount = -924.80m },
            new Transaction { Id = 45, Date = new DateOnly(2026, 5, 25), Merchant = "Watsons", Category = CategoryId.Shopping, PaymentMethod = "Credit card", Amount = -48.70m },
            new Transaction { Id = 46, Date = new DateOnly(2026, 5, 26), Merchant = "Helpling", Category = CategoryId.Housing, PaymentMethod = "Credit card", Amount = -96.00m },
            new Transaction { Id = 47, Date = new DateOnly(2026, 5, 28), Merchant = "Grab ride", Category = CategoryId.Transport, PaymentMethod = "Credit card", Amount = -61.20m },
            new Transaction { Id = 48, Date = new DateOnly(2026, 5, 29), Merchant = "Kopitiam", Category = CategoryId.Food, PaymentMethod = "PayNow", Amount = -38.50m },

            // June
            new Transaction { Id = 49, Date = new DateOnly(2026, 6, 1), Merchant = "Salary", Category = CategoryId.Income, PaymentMethod = "Bank transfer", Amount = 5200m },
            new Transaction { Id = 50, Date = new DateOnly(2026, 6, 2), Merchant = "Town Council S&CC", Category = CategoryId.Housing, PaymentMethod = "GIRO", Amount = -78.00m },
            new Transaction { Id = 51, Date = new DateOnly(2026, 6, 3), Merchant = "Singtel", Category = CategoryId.Bills, PaymentMethod = "GIRO", Amount = -48.00m },
            new Transaction { Id = 52, Date = new DateOnly(2026, 6, 5), Merchant = "SimplyGo", Category = CategoryId.Transport, PaymentMethod = "Credit card", Amount = -100.00m },
            new Transaction { Id = 53, Date = new DateOnly(2026, 6, 7), Merchant = "NTUC FairPrice", Category = CategoryId.Food, PaymentMethod = "PayNow", Amount = -168.90m },
            new Transaction { Id = 54, Date = new DateOnly(2026, 6, 8), Merchant = "StarHub", Category = CategoryId.Bills, PaymentMethod = "GIRO", Amount = -51.60m },
            new Transaction { Id = 55, Date = new DateOnly(2026, 6, 9), Merchant = "Kopitiam", Category = CategoryId.Food, PaymentMethod = "PayNow", Amount = -42.60m },
            new Transaction { Id = 56, Date = new DateOnly(2026, 6, 12), Merchant = "Helpling", Category = CategoryId.Housing, PaymentMethod = "Credit card", Amount = -120.00m },
            new Transaction { Id = 57, Date = new DateOnly(2026, 6, 13), Merchant = "Grab ride", Category = CategoryId.Transport, PaymentMethod = "Credit card", Amount = -58.60m },
            new Transaction { Id = 58, Date = new DateOnly(2026, 6, 14), Merchant = "IKEA", Category = CategoryId.Housing, PaymentMethod = "Credit card", Amount = -186.50m },
            new Transaction { Id = 59, Date = new DateOnly(2026, 6, 14), Merchant = "Tim Ho Wan", Category = CategoryId.Food, PaymentMethod = "Credit card", Amount = -46.30m },
            new Transaction { Id = 60, Date = new DateOnly(2026, 6, 15), Merchant = "SP Services", Category = CategoryId.Bills, PaymentMethod = "GIRO", Amount = -131.80m },
            new Transaction { Id = 61, Date = new DateOnly(2026, 6, 19), Merchant = "SimplyGo", Category = CategoryId.Transport, PaymentMethod = "Credit card", Amount = -80.00m },
            new Transaction { Id = 62, Date = new DateOnly(2026, 6, 20), Merchant = "Takashimaya", Category = CategoryId.Shopping, PaymentMethod = "Credit card", Amount = -737.10m },
            new Transaction { Id = 63, Date = new DateOnly(2026, 6, 21), Merchant = "NTUC FairPrice", Category = CategoryId.Food, PaymentMethod = "PayNow", Amount = -88.40m },
            new Transaction { Id = 64, Date = new DateOnly(2026, 6, 22), Merchant = "Sheng Siong", Category = CategoryId.Food, PaymentMethod = "PayNow", Amount = -92.10m },
            new Transaction { Id = 65, Date = new DateOnly(2026, 6, 25), Merchant = "Watsons", Category = CategoryId.Shopping, PaymentMethod = "Credit card", Amount = -48.70m },
            new Transaction { Id = 66, Date = new DateOnly(2026, 6, 26), Merchant = "Helpling", Category = CategoryId.Housing, PaymentMethod = "Credit card", Amount = -96.00m },
            new Transaction { Id = 67, Date = new DateOnly(2026, 6, 27), Merchant = "GrabFood", Category = CategoryId.Food, PaymentMethod = "Credit card", Amount = -54.20m },
            new Transaction { Id = 68, Date = new DateOnly(2026, 6, 28), Merchant = "Grab ride", Category = CategoryId.Transport, PaymentMethod = "Credit card", Amount = -61.20m },

            // July
            new Transaction { Id = 69, Date = new DateOnly(2026, 7, 1), Merchant = "Salary", Category = CategoryId.Income, PaymentMethod = "Bank transfer", Amount = 5200m },
            new Transaction { Id = 70, Date = new DateOnly(2026, 7, 2), Merchant = "Town Council S&CC", Category = CategoryId.Housing, PaymentMethod = "GIRO", Amount = -78.00m },
            new Transaction { Id = 71, Date = new DateOnly(2026, 7, 3), Merchant = "Singtel", Category = CategoryId.Bills, PaymentMethod = "GIRO", Amount = -48.00m },
            new Transaction { Id = 72, Date = new DateOnly(2026, 7, 5), Merchant = "SimplyGo", Category = CategoryId.Transport, PaymentMethod = "Credit card", Amount = -100.00m },
            new Transaction { Id = 73, Date = new DateOnly(2026, 7, 5), Merchant = "NTUC FairPrice", Category = CategoryId.Food, PaymentMethod = "PayNow", Amount = -181.60m },
            new Transaction { Id = 74, Date = new DateOnly(2026, 7, 8), Merchant = "StarHub", Category = CategoryId.Bills, PaymentMethod = "GIRO", Amount = -51.60m },
            new Transaction { Id = 75, Date = new DateOnly(2026, 7, 9), Merchant = "Kopitiam", Category = CategoryId.Food, PaymentMethod = "PayNow", Amount = -42.60m },
            new Transaction { Id = 76, Date = new DateOnly(2026, 7, 10), Merchant = "Grab ride", Category = CategoryId.Transport, PaymentMethod = "Credit card", Amount = -82.70m },
            new Transaction { Id = 77, Date = new DateOnly(2026, 7, 12), Merchant = "Helpling", Category = CategoryId.Housing, PaymentMethod = "Credit card", Amount = -120.00m },
            new Transaction { Id = 78, Date = new DateOnly(2026, 7, 12), Merchant = "Din Tai Fung", Category = CategoryId.Food, PaymentMethod = "Credit card", Amount = -64.90m },
            new Transaction { Id = 79, Date = new DateOnly(2026, 7, 14), Merchant = "IKEA", Category = CategoryId.Housing, PaymentMethod = "Credit card", Amount = -186.50m },
            new Transaction { Id = 80, Date = new DateOnly(2026, 7, 15), Merchant = "SP Services", Category = CategoryId.Bills, PaymentMethod = "GIRO", Amount = -138.50m },
            new Transaction { Id = 81, Date = new DateOnly(2026, 7, 17), Merchant = "Lazada", Category = CategoryId.Shopping, PaymentMethod = "Credit card", Amount = -92.80m },
            new Transaction { Id = 82, Date = new DateOnly(2026, 7, 19), Merchant = "SimplyGo", Category = CategoryId.Transport, PaymentMethod = "Credit card", Amount = -80.00m },
            new Transaction { Id = 83, Date = new DateOnly(2026, 7, 19), Merchant = "NTUC FairPrice", Category = CategoryId.Food, PaymentMethod = "PayNow", Amount = -97.40m },
            new Transaction { Id = 84, Date = new DateOnly(2026, 7, 24), Merchant = "Sheng Siong", Category = CategoryId.Food, PaymentMethod = "PayNow", Amount = -83.20m },
            new Transaction { Id = 85, Date = new DateOnly(2026, 7, 25), Merchant = "Watsons", Category = CategoryId.Shopping, PaymentMethod = "Credit card", Amount = -48.70m },
            new Transaction { Id = 86, Date = new DateOnly(2026, 7, 26), Merchant = "Helpling", Category = CategoryId.Housing, PaymentMethod = "Credit card", Amount = -96.00m },
            new Transaction { Id = 87, Date = new DateOnly(2026, 7, 26), Merchant = "Swee Choon", Category = CategoryId.Food, PaymentMethod = "PayNow", Amount = -41.30m },
            new Transaction { Id = 88, Date = new DateOnly(2026, 7, 28), Merchant = "Grab ride", Category = CategoryId.Transport, PaymentMethod = "Credit card", Amount = -61.20m },
            new Transaction { Id = 89, Date = new DateOnly(2026, 7, 30), Merchant = "Scoot", Category = CategoryId.Other, PaymentMethod = "Credit card", Amount = -1035.00m },

            // August
            new Transaction { Id = 90, Date = new DateOnly(2026, 8, 1), Merchant = "Salary", Category = CategoryId.Income, PaymentMethod = "Bank transfer", Amount = 5200m },
            new Transaction { Id = 91, Date = new DateOnly(2026, 8, 2), Merchant = "Town Council S&CC", Category = CategoryId.Housing, PaymentMethod = "GIRO", Amount = -78.00m },
            new Transaction { Id = 92, Date = new DateOnly(2026, 8, 3), Merchant = "Singtel", Category = CategoryId.Bills, PaymentMethod = "GIRO", Amount = -48.00m },
            new Transaction { Id = 93, Date = new DateOnly(2026, 8, 3), Merchant = "NTUC FairPrice", Category = CategoryId.Food, PaymentMethod = "PayNow", Amount = -186.40m },
            new Transaction { Id = 94, Date = new DateOnly(2026, 8, 5), Merchant = "SimplyGo", Category = CategoryId.Transport, PaymentMethod = "Credit card", Amount = -120.00m },
            new Transaction { Id = 95, Date = new DateOnly(2026, 8, 8), Merchant = "StarHub", Category = CategoryId.Bills, PaymentMethod = "GIRO", Amount = -51.60m },
            new Transaction { Id = 96, Date = new DateOnly(2026, 8, 8), Merchant = "Uniqlo", Category = CategoryId.Shopping, PaymentMethod = "Credit card", Amount = -119.80m },
            new Transaction { Id = 97, Date = new DateOnly(2026, 8, 9), Merchant = "Din Tai Fung", Category = CategoryId.Food, PaymentMethod = "Credit card", Amount = -58.30m },
            new Transaction { Id = 98, Date = new DateOnly(2026, 8, 10), Merchant = "Sheng Siong", Category = CategoryId.Food, PaymentMethod = "PayNow", Amount = -95.60m },
            new Transaction { Id = 99, Date = new DateOnly(2026, 8, 12), Merchant = "Helpling", Category = CategoryId.Housing, PaymentMethod = "Credit card", Amount = -120.00m },
            new Transaction { Id = 100, Date = new DateOnly(2026, 8, 13), Merchant = "Grab ride", Category = CategoryId.Transport, PaymentMethod = "Credit card", Amount = -88.40m },
            new Transaction { Id = 101, Date = new DateOnly(2026, 8, 15), Merchant = "SP Services", Category = CategoryId.Bills, PaymentMethod = "GIRO", Amount = -125.40m },
            new Transaction { Id = 102, Date = new DateOnly(2026, 8, 16), Merchant = "Jumbo Seafood", Category = CategoryId.Food, PaymentMethod = "Credit card", Amount = -142.00m },
            new Transaction { Id = 103, Date = new DateOnly(2026, 8, 17), Merchant = "IKEA", Category = CategoryId.Housing, PaymentMethod = "Credit card", Amount = -214.00m },
            new Transaction { Id = 104, Date = new DateOnly(2026, 8, 18), Merchant = "Shopee", Category = CategoryId.Shopping, PaymentMethod = "Credit card", Amount = -78.30m },
            new Transaction { Id = 105, Date = new DateOnly(2026, 8, 19), Merchant = "SimplyGo", Category = CategoryId.Transport, PaymentMethod = "Credit card", Amount = -80.00m },
            new Transaction { Id = 106, Date = new DateOnly(2026, 8, 20), Merchant = "Mr DIY", Category = CategoryId.Housing, PaymentMethod = "Credit card", Amount = -104.00m },
            new Transaction { Id = 107, Date = new DateOnly(2026, 8, 22), Merchant = "GrabFood", Category = CategoryId.Food, PaymentMethod = "Credit card", Amount = -64.70m },
            new Transaction { Id = 108, Date = new DateOnly(2026, 8, 23), Merchant = "Wedding ang bao", Category = CategoryId.Other, PaymentMethod = "PayNow", Amount = -200.00m },
            new Transaction { Id = 109, Date = new DateOnly(2026, 8, 24), Merchant = "NTUC FairPrice", Category = CategoryId.Food, PaymentMethod = "PayNow", Amount = -80.00m },
            new Transaction { Id = 110, Date = new DateOnly(2026, 8, 25), Merchant = "Watsons", Category = CategoryId.Shopping, PaymentMethod = "Credit card", Amount = -54.90m },
            new Transaction { Id = 111, Date = new DateOnly(2026, 8, 26), Merchant = "Helpling", Category = CategoryId.Housing, PaymentMethod = "Credit card", Amount = -96.00m },
            new Transaction { Id = 112, Date = new DateOnly(2026, 8, 28), Merchant = "Kopitiam", Category = CategoryId.Food, PaymentMethod = "PayNow", Amount = -45.00m },
            new Transaction { Id = 113, Date = new DateOnly(2026, 8, 29), Merchant = "Grab ride", Category = CategoryId.Transport, PaymentMethod = "Credit card", Amount = -59.60m },
            new Transaction { Id = 114, Date = new DateOnly(2026, 8, 30), Merchant = "SPCA donation", Category = CategoryId.Other, PaymentMethod = "PayNow", Amount = -13.00m },

            // September
            new Transaction { Id = 115, Date = new DateOnly(2026, 9, 1), Merchant = "NTUC FairPrice", Category = CategoryId.Food, PaymentMethod = "PayNow", Amount = -38.40m },
            new Transaction { Id = 116, Date = new DateOnly(2026, 9, 1), Merchant = "Toast Box", Category = CategoryId.Food, PaymentMethod = "Credit card", Amount = -8.60m },
            new Transaction { Id = 117, Date = new DateOnly(2026, 9, 1), Merchant = "SimplyGo", Category = CategoryId.Transport, PaymentMethod = "Credit card", Amount = -13.00m },
            new Transaction { Id = 118, Date = new DateOnly(2026, 9, 2), Merchant = "Town Council S&CC", Category = CategoryId.Housing, PaymentMethod = "GIRO", Amount = -78.00m },
            new Transaction { Id = 119, Date = new DateOnly(2026, 9, 2), Merchant = "Ya Kun Kaya Toast", Category = CategoryId.Food, PaymentMethod = "PayNow", Amount = -7.20m },
            new Transaction { Id = 120, Date = new DateOnly(2026, 9, 2), Merchant = "Grab ride", Category = CategoryId.Transport, PaymentMethod = "Credit card", Amount = -24.80m },
            new Transaction { Id = 121, Date = new DateOnly(2026, 9, 3), Merchant = "Singtel", Category = CategoryId.Bills, PaymentMethod = "GIRO", Amount = -48.00m },
            new Transaction { Id = 122, Date = new DateOnly(2026, 9, 3), Merchant = "Koufu", Category = CategoryId.Food, PaymentMethod = "PayNow", Amount = -6.50m },
            new Transaction { Id = 123, Date = new DateOnly(2026, 9, 3), Merchant = "Popular Bookstore", Category = CategoryId.Shopping, PaymentMethod = "Credit card", Amount = -40.50m },
            new Transaction { Id = 124, Date = new DateOnly(2026, 9, 4), Merchant = "Fortytwo", Category = CategoryId.Housing, PaymentMethod = "Credit card", Amount = -189.00m },
            new Transaction { Id = 125, Date = new DateOnly(2026, 9, 4), Merchant = "Mr DIY", Category = CategoryId.Housing, PaymentMethod = "Credit card", Amount = -39.00m },
            new Transaction { Id = 126, Date = new DateOnly(2026, 9, 4), Merchant = "Sheng Siong", Category = CategoryId.Food, PaymentMethod = "PayNow", Amount = -29.40m },
            new Transaction { Id = 127, Date = new DateOnly(2026, 9, 4), Merchant = "Kopitiam", Category = CategoryId.Food, PaymentMethod = "PayNow", Amount = -14.60m },
            new Transaction { Id = 128, Date = new DateOnly(2026, 9, 4), Merchant = "Grab ride", Category = CategoryId.Transport, PaymentMethod = "Credit card", Amount = -40.00m },
            new Transaction { Id = 129, Date = new DateOnly(2026, 9, 5), Merchant = "SimplyGo", Category = CategoryId.Transport, PaymentMethod = "Credit card", Amount = -20.00m },
            new Transaction { Id = 130, Date = new DateOnly(2026, 9, 5), Merchant = "McDonald's", Category = CategoryId.Food, PaymentMethod = "Credit card", Amount = -12.90m },
            new Transaction { Id = 131, Date = new DateOnly(2026, 9, 5), Merchant = "Starbucks", Category = CategoryId.Food, PaymentMethod = "Credit card", Amount = -12.10m },
            new Transaction { Id = 132, Date = new DateOnly(2026, 9, 6), Merchant = "NTUC FairPrice", Category = CategoryId.Food, PaymentMethod = "PayNow", Amount = -42.30m },
            new Transaction { Id = 133, Date = new DateOnly(2026, 9, 6), Merchant = "Maxwell Food Centre", Category = CategoryId.Food, PaymentMethod = "PayNow", Amount = -11.70m },
            new Transaction { Id = 134, Date = new DateOnly(2026, 9, 6), Merchant = "Grab ride", Category = CategoryId.Transport, PaymentMethod = "Credit card", Amount = -16.00m },
            new Transaction { Id = 135, Date = new DateOnly(2026, 9, 7), Merchant = "Jumbo Seafood", Category = CategoryId.Food, PaymentMethod = "Credit card", Amount = -98.00m },
            new Transaction { Id = 136, Date = new DateOnly(2026, 9, 7), Merchant = "Grab ride", Category = CategoryId.Transport, PaymentMethod = "Credit card", Amount = -32.00m },
            new Transaction { Id = 137, Date = new DateOnly(2026, 9, 8), Merchant = "StarHub", Category = CategoryId.Bills, PaymentMethod = "GIRO", Amount = -51.60m },
            new Transaction { Id = 138, Date = new DateOnly(2026, 9, 8), Merchant = "Old Chang Kee", Category = CategoryId.Food, PaymentMethod = "PayNow", Amount = -5.40m },
            new Transaction { Id = 139, Date = new DateOnly(2026, 9, 8), Merchant = "Watsons", Category = CategoryId.Shopping, PaymentMethod = "Credit card", Amount = -31.00m },
            new Transaction { Id = 140, Date = new DateOnly(2026, 9, 9), Merchant = "Helpling", Category = CategoryId.Housing, PaymentMethod = "Credit card", Amount = -60.00m },
            new Transaction { Id = 141, Date = new DateOnly(2026, 9, 9), Merchant = "Hai Di Lao", Category = CategoryId.Food, PaymentMethod = "Credit card", Amount = -70.00m },
            new Transaction { Id = 142, Date = new DateOnly(2026, 9, 9), Merchant = "SimplyGo", Category = CategoryId.Transport, PaymentMethod = "Credit card", Amount = -20.00m },
            new Transaction { Id = 143, Date = new DateOnly(2026, 9, 10), Merchant = "Shopee", Category = CategoryId.Shopping, PaymentMethod = "Credit card", Amount = -54.90m },
            new Transaction { Id = 144, Date = new DateOnly(2026, 9, 10), Merchant = "Toast Box", Category = CategoryId.Food, PaymentMethod = "Credit card", Amount = -7.10m },
            new Transaction { Id = 145, Date = new DateOnly(2026, 9, 10), Merchant = "GrabFood", Category = CategoryId.Food, PaymentMethod = "Credit card", Amount = -10.00m },
            new Transaction { Id = 146, Date = new DateOnly(2026, 9, 11), Merchant = "CoolTech Aircon", Category = CategoryId.Housing, PaymentMethod = "PayNow", Amount = -96.00m },
            new Transaction { Id = 147, Date = new DateOnly(2026, 9, 11), Merchant = "NTUC FairPrice", Category = CategoryId.Food, PaymentMethod = "PayNow", Amount = -29.85m },
            new Transaction { Id = 148, Date = new DateOnly(2026, 9, 11), Merchant = "Tim Ho Wan", Category = CategoryId.Food, PaymentMethod = "Credit card", Amount = -14.15m },
            new Transaction { Id = 149, Date = new DateOnly(2026, 9, 12), Merchant = "Guardian", Category = CategoryId.Shopping, PaymentMethod = "Credit card", Amount = -22.40m },
            new Transaction { Id = 150, Date = new DateOnly(2026, 9, 12), Merchant = "Swee Choon", Category = CategoryId.Food, PaymentMethod = "PayNow", Amount = -32.60m },
            new Transaction { Id = 151, Date = new DateOnly(2026, 9, 13), Merchant = "Lazada", Category = CategoryId.Shopping, PaymentMethod = "Credit card", Amount = -74.80m },
            new Transaction { Id = 152, Date = new DateOnly(2026, 9, 13), Merchant = "Koufu", Category = CategoryId.Food, PaymentMethod = "PayNow", Amount = -9.20m },
            new Transaction { Id = 153, Date = new DateOnly(2026, 9, 13), Merchant = "SimplyGo", Category = CategoryId.Transport, PaymentMethod = "Credit card", Amount = -20.00m },
            new Transaction { Id = 154, Date = new DateOnly(2026, 9, 14), Merchant = "Kopitiam", Category = CategoryId.Food, PaymentMethod = "PayNow", Amount = -8.20m },
            new Transaction { Id = 155, Date = new DateOnly(2026, 9, 15), Merchant = "SimplyGo", Category = CategoryId.Transport, PaymentMethod = "Credit card", Amount = -20.00m },
            new Transaction { Id = 156, Date = new DateOnly(2026, 9, 15), Merchant = "Ya Kun Kaya Toast", Category = CategoryId.Food, PaymentMethod = "PayNow", Amount = -8.35m },
            new Transaction { Id = 157, Date = new DateOnly(2026, 9, 16), Merchant = "Helpling", Category = CategoryId.Housing, PaymentMethod = "Credit card", Amount = -60.00m },
            new Transaction { Id = 158, Date = new DateOnly(2026, 9, 16), Merchant = "NTUC FairPrice", Category = CategoryId.Food, PaymentMethod = "PayNow", Amount = -23.60m },
            new Transaction { Id = 159, Date = new DateOnly(2026, 9, 16), Merchant = "SimplyGo", Category = CategoryId.Transport, PaymentMethod = "Credit card", Amount = -40.00m },
            new Transaction { Id = 160, Date = new DateOnly(2026, 9, 17), Merchant = "Ichiban Sushi", Category = CategoryId.Food, PaymentMethod = "Credit card", Amount = -42.00m },
            new Transaction { Id = 161, Date = new DateOnly(2026, 9, 17), Merchant = "IKEA", Category = CategoryId.Housing, PaymentMethod = "Credit card", Amount = -90.00m },
            new Transaction { Id = 162, Date = new DateOnly(2026, 9, 19), Merchant = "Grab ride", Category = CategoryId.Transport, PaymentMethod = "Credit card", Amount = -45.40m },
            new Transaction { Id = 163, Date = new DateOnly(2026, 9, 19), Merchant = "Decathlon", Category = CategoryId.Shopping, PaymentMethod = "Credit card", Amount = -35.50m },
            new Transaction { Id = 164, Date = new DateOnly(2026, 9, 19), Merchant = "Tim Ho Wan", Category = CategoryId.Food, PaymentMethod = "Credit card", Amount = -21.00m },
            new Transaction { Id = 165, Date = new DateOnly(2026, 9, 19), Merchant = "NTUC FairPrice", Category = CategoryId.Food, PaymentMethod = "PayNow", Amount = -17.50m },
            new Transaction { Id = 166, Date = new DateOnly(2026, 9, 19), Merchant = "Starbucks", Category = CategoryId.Food, PaymentMethod = "Credit card", Amount = -9.80m },
        };

        public static readonly Budget[] Budgets = new Budget[]
        {
            new Budget { Id = 1, Category = CategoryId.Food, Year = 2026, Month = 9, Limit = 750m },
            new Budget { Id = 2, Category = CategoryId.Housing, Year = 2026, Month = 9, Limit = 700m },
            new Budget { Id = 3, Category = CategoryId.Transport, Year = 2026, Month = 9, Limit = 400m },
            new Budget { Id = 4, Category = CategoryId.Shopping, Year = 2026, Month = 9, Limit = 300m },
            new Budget { Id = 5, Category = CategoryId.Bills, Year = 2026, Month = 9, Limit = 300m },
            new Budget { Id = 6, Category = CategoryId.Other, Year = 2026, Month = 9, Limit = 550m },
        };
    }
}
